language: objective-c
xcode_project: PPJEmailPickerDemo.xcodeproj 
xcode_scheme: PPJEmailPickerDemoTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
