language: objective-c
xcode_project: PPJEmailPickerDemo.xcodeproj 
xcode_scheme: PPJEmailPickerDemoTests
osx_image: xcode83
xcode_sdk: iphonesimulator
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script: set -o pipefail &&  xcodebuild test -project PPJEmailPickerDemo.xcodeproj -scheme PPJEmailPickerDemoTests -sdk iphonesimulator10.3 | xcpretty
